/**
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 * Programa: GCSRE0092
 */
package br.com.gcs.visao;

import br.com.modelo.SessaoUsuario;
import br.com.scgos.gcs.visao.Materiais;

/**
 *
 * @author cristiano
 */
public class ImprimirMateriais extends javax.swing.JDialog {
    private static SessaoUsuario su;
    private static String cdMaterialIni;
    private static String cdMaterialFim;
    private static String cdGrupoIni;
    private static String cdGrupoFim;
    private static String cdSubGrupoIni;
    private static String cdSubGrupoFim;

    /**
     * Creates new form ImprimirMaterial
     */
    public ImprimirMateriais(java.awt.Frame parent, boolean modal, String cdMaterial, String cdGrupo, String cdSubGrupo, SessaoUsuario su) {
        super(parent, modal);
        this.su = su;
        this.cdMaterialIni = cdMaterial;
        this.cdMaterialFim = cdMaterial;
        this.cdGrupoIni = cdGrupo;
        this.cdGrupoFim = cdGrupo;
        this.cdSubGrupoIni = cdSubGrupo;
        this.cdSubGrupoFim = cdSubGrupo;
        setLocationRelativeTo(null);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        upRegistros();
    }
    private void upRegistros(){
        jTexCodigoMaterialDe.setText(cdMaterialIni);
        jTexCodigoMaterialAte.setText(cdMaterialFim);
        jTexCodigoGrupoDe.setText(cdGrupoIni);
        jTexCodigoGrupoAte.setText(cdGrupoFim);
        jTexCodigoSubGrupoDe.setText(cdSubGrupoIni);
        jTexCodigoSubGrupoAte.setText(cdSubGrupoFim);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanFiltro = new javax.swing.JPanel();
        jLabGrupoDe = new javax.swing.JLabel();
        jTexCodigoGrupoDe = new javax.swing.JTextField();
        jLabGrupoAte = new javax.swing.JLabel();
        jTexCodigoGrupoAte = new javax.swing.JTextField();
        jLabSubGrupoDe = new javax.swing.JLabel();
        jTexCodigoSubGrupoDe = new javax.swing.JTextField();
        jLabSubGrupoAte = new javax.swing.JLabel();
        jTexCodigoSubGrupoAte = new javax.swing.JTextField();
        jButImprimir = new javax.swing.JButton();
        jLabMaterialDe = new javax.swing.JLabel();
        jTexCodigoMaterialDe = new javax.swing.JTextField();
        jLabMaterialAte = new javax.swing.JLabel();
        jTexCodigoMaterialAte = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Relatório de Materiais");

        jPanFiltro.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Filtros", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabGrupoDe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabGrupoDe.setText("Grupo de:");

        jLabGrupoAte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabGrupoAte.setText("Grupo até:");

        jLabSubGrupoDe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabSubGrupoDe.setText("Sub Grupo de:");

        jLabSubGrupoAte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabSubGrupoAte.setText("Sub Grupo até:");

        jButImprimir.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jButImprimir.setText("Imprimir");
        jButImprimir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButImprimirActionPerformed(evt);
            }
        });

        jLabMaterialDe.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabMaterialDe.setText("Material de:");

        jLabMaterialAte.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabMaterialAte.setText("Material até:");

        javax.swing.GroupLayout jPanFiltroLayout = new javax.swing.GroupLayout(jPanFiltro);
        jPanFiltro.setLayout(jPanFiltroLayout);
        jPanFiltroLayout.setHorizontalGroup(
            jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanFiltroLayout.createSequentialGroup()
                .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanFiltroLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButImprimir))
                    .addGroup(jPanFiltroLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabSubGrupoDe)
                            .addComponent(jLabGrupoDe)
                            .addComponent(jLabMaterialDe))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jTexCodigoSubGrupoDe, javax.swing.GroupLayout.PREFERRED_SIZE, 1, Short.MAX_VALUE)
                                .addComponent(jTexCodigoGrupoDe, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jTexCodigoMaterialDe, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12)
                        .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanFiltroLayout.createSequentialGroup()
                                .addGap(63, 63, 63)
                                .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabGrupoAte, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabSubGrupoAte, javax.swing.GroupLayout.Alignment.TRAILING)))
                            .addComponent(jLabMaterialAte, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTexCodigoGrupoAte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexCodigoSubGrupoAte, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTexCodigoMaterialAte, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 66, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanFiltroLayout.setVerticalGroup(
            jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanFiltroLayout.createSequentialGroup()
                .addContainerGap(18, Short.MAX_VALUE)
                .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabMaterialAte)
                        .addComponent(jTexCodigoMaterialAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jTexCodigoMaterialDe, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabMaterialDe, javax.swing.GroupLayout.Alignment.TRAILING))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanFiltroLayout.createSequentialGroup()
                        .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabGrupoAte)
                            .addComponent(jTexCodigoGrupoAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabSubGrupoAte)
                            .addComponent(jTexCodigoSubGrupoAte, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanFiltroLayout.createSequentialGroup()
                        .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabGrupoDe)
                            .addComponent(jTexCodigoGrupoDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanFiltroLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabSubGrupoDe)
                            .addComponent(jTexCodigoSubGrupoDe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButImprimir)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanFiltro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanFiltro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButImprimirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButImprimirActionPerformed
        // TODO add your handling code here:
        if(!jTexCodigoMaterialDe.getText().isEmpty())
            cdMaterialIni = jTexCodigoMaterialDe.getText().trim();
        else
            cdMaterialIni = "0";
        if(!jTexCodigoMaterialAte.getText().isEmpty())
            cdMaterialFim = jTexCodigoMaterialAte.getText().trim();
        else
            cdMaterialFim = "99999999999999999";
        if(!jTexCodigoGrupoDe.getText().isEmpty())
            cdGrupoIni = jTexCodigoGrupoDe.getText().trim();
        else
            cdGrupoIni = "0";
        if(!jTexCodigoGrupoAte.getText().isEmpty())
            cdGrupoFim = jTexCodigoGrupoAte.getText().trim();
        else
            cdGrupoFim = "999";
        if(!jTexCodigoSubGrupoDe.getText().isEmpty())
            cdSubGrupoIni = jTexCodigoSubGrupoDe.getText().trim();
        else
            cdSubGrupoIni = "0";
        if(!jTexCodigoSubGrupoAte.getText().isEmpty())
            cdSubGrupoFim = jTexCodigoSubGrupoAte.getText().trim();
        else
            cdSubGrupoFim = "999";
        new Materiais().abrirRelatorio(cdMaterialIni, cdMaterialFim, cdGrupoIni, cdGrupoFim, cdSubGrupoIni,cdSubGrupoFim,su);
        this.dispose();
    }//GEN-LAST:event_jButImprimirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ImprimirMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ImprimirMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ImprimirMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ImprimirMateriais.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ImprimirMateriais dialog = new ImprimirMateriais(new javax.swing.JFrame(), true, cdMaterialIni, cdGrupoIni, cdSubGrupoIni, su);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButImprimir;
    private javax.swing.JLabel jLabGrupoAte;
    private javax.swing.JLabel jLabGrupoDe;
    private javax.swing.JLabel jLabMaterialAte;
    private javax.swing.JLabel jLabMaterialDe;
    private javax.swing.JLabel jLabSubGrupoAte;
    private javax.swing.JLabel jLabSubGrupoDe;
    private javax.swing.JPanel jPanFiltro;
    private javax.swing.JTextField jTexCodigoGrupoAte;
    private javax.swing.JTextField jTexCodigoGrupoDe;
    private javax.swing.JTextField jTexCodigoMaterialAte;
    private javax.swing.JTextField jTexCodigoMaterialDe;
    private javax.swing.JTextField jTexCodigoSubGrupoAte;
    private javax.swing.JTextField jTexCodigoSubGrupoDe;
    // End of variables declaration//GEN-END:variables
}
