/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.zteste.gui;

import br.com.DAO.UnidadeNegocioDAO;
import br.com.controle.CUnidadeNegocio;
import br.com.modelo.SessaoUsuario;
import br.com.modelo.UnidadeNegocio;
import br.com.modelo.VerificarTecla;
import java.awt.event.KeyEvent;
import java.awt.event.KeyListener;
import java.sql.Connection;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author cristiano
 */
public class IncluirLinhaTabela extends javax.swing.JFrame {

    private static Connection conexao;
    private static SessaoUsuario usu;
    private final DefaultTableModel Conteudo = new DefaultTableModel();
    JTable t = new JTable(Conteudo);
    DefaultTableModel modelo = new DefaultTableModel();

    private UnidadeNegocio modunid;
    private List<UnidadeNegocio> resultado;
    private CUnidadeNegocio cunid;
    private UnidadeNegocioDAO unidao;

    /**
     * Creates new form IncluirLinhaTabela
     */
    public IncluirLinhaTabela(Connection conexao, SessaoUsuario usu) {
        this.conexao = conexao;
        this.usu = usu;
        Conteudo.addColumn("Cod");
        Conteudo.addColumn("Nome");
        Conteudo.addColumn("Situacao");
        initComponents();
        setaInicio();
        mudarLinha();
    }

    // Método para pesquisar o registro
    private void setaInicio() {
        modunid = new UnidadeNegocio();
        cunid = new CUnidadeNegocio(conexao);
        try {
            unidao = new UnidadeNegocioDAO(conexao);
        } catch (SQLException ex) {
            Logger.getLogger(IncluirLinhaTabela.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    // Método para Pesquisar o registro
    private void pesquisaRegistro() {
        resultado = new ArrayList<UnidadeNegocio>();
        String sql = "select u.cd_unidnegocio as 'Cod.',"
                + "u.nome_unidnegocio as Nome,"
                + "u.situacao as Situacao "
                + "from pgsunidnegocio as u";
        try {
            unidao.selecionar(resultado, sql);
            unidao.setQuery(sql);
        } catch (SQLException ex) {
            Logger.getLogger(IncluirLinhaTabela.class.getName()).log(Level.SEVERE, null, ex);
        } catch (IllegalStateException ex) {
            Logger.getLogger(IncluirLinhaTabela.class.getName()).log(Level.SEVERE, null, ex);
        }
        jTabUnidNegocio.setModel(unidao);
    }

    // Método para criar um listiner na tabela para verificar mudança de linha
    private void mudarLinha() {
        jTabUnidNegocio.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
            }

        });
        jTabUnidNegocio.addKeyListener(new KeyListener() {
            public boolean isCellEditable(int row, int column) {
                return true;
            }

            @Override
            public void keyTyped(KeyEvent e) {
            }

            @Override
            public void keyPressed(KeyEvent e) {
                VerificarTecla vt = new VerificarTecla();
                if ("ABAIXO".equals(vt.VerificarTecla(e).toUpperCase())) {
                    JOptionPane.showMessageDialog(null, vt.VerificarTecla(e));
                    inserirLinha("2", "TEste", "A");
                }
            }

            @Override
            public void keyReleased(KeyEvent e) {
            }

            public void inserirLinha(String cod, String nome, String situacao) {
                modelo = (DefaultTableModel) t.getModel();
                jTabUnidNegocio.setModel(modelo);
                modelo.addRow(new Object[]{null, null, null});
            }
        });
    }

    public void carregaModelo() {
        for (int i = 0; i <= resultado.size(); i++) {
            modunid = resultado.get(+i);
            modelo.addRow(new Object[]{modunid.getCdUnidNegocio(), modunid.getNomeUnidNegocio(), modunid.getSituacao()});
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTabUnidNegocio = new javax.swing.JTable();
        jButPesquisar = new javax.swing.JButton();
        jButAtualizarDao = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButCarregarModelo = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabUnidNegocio.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Cod.", "Nome", "Situacao"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTabUnidNegocio);

        jButPesquisar.setText("Pesquisar");
        jButPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButPesquisarActionPerformed(evt);
            }
        });

        jButAtualizarDao.setText("atuallizarDao");
        jButAtualizarDao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButAtualizarDaoActionPerformed(evt);
            }
        });

        jButton2.setText("atualiarModelo");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButCarregarModelo.setText("Carregar Modelo");
        jButCarregarModelo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButCarregarModeloActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButPesquisar)
                    .addComponent(jButAtualizarDao)
                    .addComponent(jButton2)
                    .addComponent(jButCarregarModelo))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButPesquisar)
                        .addGap(18, 18, 18)
                        .addComponent(jButAtualizarDao)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButCarregarModelo))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 339, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(88, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButPesquisarActionPerformed
        pesquisaRegistro();
    }//GEN-LAST:event_jButPesquisarActionPerformed

    private void jButAtualizarDaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButAtualizarDaoActionPerformed
        // TODO add your handling code here:
        jTabUnidNegocio.setModel(unidao);

    }//GEN-LAST:event_jButAtualizarDaoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        jTabUnidNegocio.setModel(modelo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButCarregarModeloActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButCarregarModeloActionPerformed
        carregaModelo();
    }//GEN-LAST:event_jButCarregarModeloActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(IncluirLinhaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(IncluirLinhaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(IncluirLinhaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(IncluirLinhaTabela.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new IncluirLinhaTabela(conexao, usu).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButAtualizarDao;
    private javax.swing.JButton jButCarregarModelo;
    private javax.swing.JButton jButPesquisar;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTabUnidNegocio;
    // End of variables declaration//GEN-END:variables
}
