/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.zteste.gui;

import com.sun.javafx.collections.ListListenerHelper;
import javax.swing.JOptionPane;
import javax.swing.event.ListSelectionListener;
import javax.swing.event.TreeSelectionEvent;
import javax.swing.event.TreeSelectionListener;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author cristiano
 */
public class ManterContrato extends javax.swing.JFrame {

    String node;
    boolean incluindo;
    Object parent;
    Object child;

    /**
     * Creates new form ManterContrato
     */
    public ManterContrato() {
        initComponents();
        monitoraLinha();
    }

    private void monitoraLinha() {
        jTreContrato.getSelectionModel().addTreeSelectionListener(new TreeSelectionListener() {
            @Override
            public void valueChanged(TreeSelectionEvent e) {
                if (!incluindo && jTreContrato.getSelectionPath().toString() != null) {
                    node = jTreContrato.getSelectionPath().getLastPathComponent().toString();
                    parent = jTreContrato.getSelectionModel().getLeadSelectionRow();
                    child = jTreContrato.getSelectionModel().getLeadSelectionPath().getPathCount();
                    JOptionPane.showMessageDialog(null, "Cláusula do Contrado: " + node +
                            "\nNúmero da Linha: " + parent + "\nNivel do Nó: " + child);
                }
            }
        });
    }

    private void adicionarNode() {
        incluindo = true;
        DefaultMutableTreeNode treeNode1 = new DefaultMutableTreeNode("Instrumento Particular de Prestação de Serviço");
        DefaultMutableTreeNode treeNode2 = new DefaultMutableTreeNode("1 - Das partes");
        DefaultMutableTreeNode treeNode3;
        treeNode3 = new DefaultMutableTreeNode("Do Contratante");
        treeNode2.add(treeNode3);
        treeNode3 = new DefaultMutableTreeNode("Da Contratada");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);
        treeNode2 = new DefaultMutableTreeNode("2 - Objeto");
        treeNode3  = new DefaultMutableTreeNode("Parágrafo 1");
        treeNode2.add(treeNode3);
        treeNode1.add(treeNode2);

        jTreContrato.setModel(new DefaultTreeModel(treeNode1));
        incluindo = false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTreContrato = new javax.swing.JTree();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();
        jMenAdicionarNivel = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(870, 763));
        setMinimumSize(new java.awt.Dimension(870, 763));

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Instrumento Particular de Contrato");
        jTreContrato.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane1.setViewportView(jTreContrato);

        jMenu1.setText("Arquivo");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Editar");

        jMenAdicionarNivel.setText("Adicionar Nivel");
        jMenAdicionarNivel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenAdicionarNivelActionPerformed(evt);
            }
        });
        jMenu2.add(jMenAdicionarNivel);

        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 311, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(549, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 580, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(151, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenAdicionarNivelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenAdicionarNivelActionPerformed
        adicionarNode();
    }//GEN-LAST:event_jMenAdicionarNivelActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ManterContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ManterContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ManterContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ManterContrato.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ManterContrato().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem jMenAdicionarNivel;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTree jTreContrato;
    // End of variables declaration//GEN-END:variables
}
