/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gfc.visao;

import br.com.gfc.dao.ConsultaTitulos;
import br.com.modelo.SessaoUsuario;
import java.io.File;
import java.io.IOException;
import java.sql.Connection;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.SwingConstants;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.JTableHeader;
import br.com.modelo.FormatarValor;
import java.awt.Dimension;
import java.awt.Toolkit;
import javax.swing.JFrame;

/**
 *
 * @author Cristiano de Oliveira Sousa criado em 20/08/2018
 *
 */
public class PesquisarTitulosFiltro extends javax.swing.JDialog {

    private static Connection conexao;
    private static SessaoUsuario su;
    private ConsultaTitulos ttdao;
    private int linhaTitulos;
    private static String sqlTitulo;
    DefaultTableCellRenderer alinTitulo;
    DefaultTableCellRenderer alinLinha;
    JTableHeader titulo;

    /**
     * Creates new form PesquisarTitulosFiltro
     */
    public PesquisarTitulosFiltro(java.awt.Frame parent, boolean modal, Connection conexao, SessaoUsuario su, String sql) {
        super(parent, modal);
        this.conexao = conexao;
        sqlTitulo = sql;
        setLocationRelativeTo(null);
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        centralizarComponente();
        buscarTitulos();
    }

    // método para centralizar componente
    public void centralizarComponente() {
        Dimension ds = Toolkit.getDefaultToolkit().getScreenSize();
        Dimension dw = getSize();
        setLocation((ds.width - dw.width) / 2, (ds.height - dw.height) / 2);
    }

    /**
     * Método para buscar lancamentos financeiros
     */
    private void buscarTitulos() {
        linhaTitulos = 0;
        try {
            //mensagem(sqlTitulo);
            ttdao = new ConsultaTitulos(conexao);
            ttdao.setQuery(sqlTitulo);
            jTabTitulo.setModel(ttdao);
            alinharTabela(jTabTitulo, 8, 11, 12);
            ttdao.ajustarTabela(jTabTitulo, 30, 5, 5, 5, 30, 200, 20, 5, 20, 30, 30, 20, 20, 20);
            jForValorTotLanc.setText(String.valueOf(ttdao.getTotPrevisaoPag() + ttdao.getTotPrevisaoRec() + ttdao.getTotTitulosPag() + ttdao.getTotTitulosRec()));
        } catch (Exception ex) {
            mensagem("Erro geral na busca dos Títulos!\nErro: " + ex);
        }
    }

    /**
     * Método para alinhas célula e título da tabela
     *
     * @param tabela
     * @param col Índice das culunas que serão alinhadas
     */
    private void alinharTabela(JTable tabela, int... col) {
        alinLinha = new DefaultTableCellRenderer();
        alinLinha.setHorizontalAlignment(SwingConstants.RIGHT);
        titulo = tabela.getTableHeader();
        alinTitulo = (DefaultTableCellRenderer) titulo.getDefaultRenderer();
        alinTitulo.setHorizontalAlignment(SwingConstants.CENTER);
        alinTitulo.setFont(new java.awt.Font("Tahoma", 2, 14));
        int coluna = 0;
        for (int i : col) {
            coluna = i;
            tabela.getColumnModel().getColumn(coluna).setCellRenderer(alinLinha);
        }
    }

    /**
     * Método para exportar títulos para excel
     */
    private void exportarTítulos() {
        try {
            ttdao.exportarExcel(new File(ttdao.gerarArquivo()), "Títulos");
        } catch (IOException io) {
            mensagem("Erro na gravação do arquivo!\nErro: " + io);
        }
    }

    /**
     * Método para retornar mensagem na tela
     *
     * @param msg String com mensagem para ser mostrada
     */
    private void mensagem(String msg) {
        JOptionPane.showMessageDialog(null, msg);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTabTitulo = new javax.swing.JTable();
        jPanBotoesTitulo2 = new javax.swing.JPanel();
        jButLancamento2 = new javax.swing.JButton();
        jButExportExcel2 = new javax.swing.JButton();
        jLabValorTotLanc = new javax.swing.JLabel();
        jForValorTotLanc = new FormatarValor(FormatarValor.NUMERO);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Títulos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 13))); // NOI18N

        jTabTitulo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Lancamento", "Tipo", "TpDoc", "Emissão", "Cliente", "Titulo", "Parc", "Valor", "Vencimento", "Liquidação", "Valor Liq.", "Saldo", "Situação"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.Double.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTabTitulo);

        jPanBotoesTitulo2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButLancamento2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButLancamento2.setText("Lançamento");
        jButLancamento2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButLancamento2ActionPerformed(evt);
            }
        });

        jButExportExcel2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jButExportExcel2.setText("Exportar p/ Excel");
        jButExportExcel2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButExportExcel2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanBotoesTitulo2Layout = new javax.swing.GroupLayout(jPanBotoesTitulo2);
        jPanBotoesTitulo2.setLayout(jPanBotoesTitulo2Layout);
        jPanBotoesTitulo2Layout.setHorizontalGroup(
            jPanBotoesTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanBotoesTitulo2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButLancamento2, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(147, 147, 147)
                .addComponent(jButExportExcel2)
                .addContainerGap())
        );
        jPanBotoesTitulo2Layout.setVerticalGroup(
            jPanBotoesTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanBotoesTitulo2Layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addGroup(jPanBotoesTitulo2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButLancamento2)
                    .addComponent(jButExportExcel2))
                .addGap(5, 5, 5))
        );

        jLabValorTotLanc.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jLabValorTotLanc.setText("Valor Total Lançamentos:");

        jForValorTotLanc.setEditable(false);
        jForValorTotLanc.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 1338, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanBotoesTitulo2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabValorTotLanc)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jForValorTotLanc, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabValorTotLanc)
                    .addComponent(jForValorTotLanc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanBotoesTitulo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButLancamento2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButLancamento2ActionPerformed
        this.setModalityType(ModalityType.MODELESS);
        new ManterTitulos(su, conexao, String.format("%s", jTabTitulo.getValueAt(jTabTitulo.getSelectedRow(), 0))).setVisible(rootPaneCheckingEnabled);
        this.setModal(false);
    }//GEN-LAST:event_jButLancamento2ActionPerformed

    private void jButExportExcel2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButExportExcel2ActionPerformed
        this.setModal(false);
        exportarTítulos();
    }//GEN-LAST:event_jButExportExcel2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PesquisarTitulosFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PesquisarTitulosFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PesquisarTitulosFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PesquisarTitulosFiltro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                PesquisarTitulosFiltro dialog = new PesquisarTitulosFiltro(new javax.swing.JFrame(), true, conexao, su, sqlTitulo);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButExportExcel;
    private javax.swing.JButton jButExportExcel1;
    private javax.swing.JButton jButExportExcel2;
    private javax.swing.JButton jButLancamento;
    private javax.swing.JButton jButLancamento1;
    private javax.swing.JButton jButLancamento2;
    private javax.swing.JButton jButLiquidar;
    private javax.swing.JButton jButLiquidar1;
    private javax.swing.JFormattedTextField jForValorTotLanc;
    private javax.swing.JLabel jLabValorTotLanc;
    private javax.swing.JPanel jPanBotoesTitulo;
    private javax.swing.JPanel jPanBotoesTitulo1;
    private javax.swing.JPanel jPanBotoesTitulo2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTabTitulo;
    // End of variables declaration//GEN-END:variables
}
